- COMETwebapp.Tests/Viewer/MatrixExtensionsTests.cs
- COMETwebapp.Tests/Viewer/PrimitivesTests.cs
- COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
- COMETwebapp/Primitives/BasicPrimitive.cs
- COMETwebapp/Primitives/Primitive.cs
- COMETwebapp/Primitives/ShapeFactory.cs
- COMETwebapp/Scene.cs
- COMETwebapp/Utilities/MatrixExtensions.cs
- COMETwebapp/wwwroot/Scripts/babylonInterop.js
The basic shapes can now be positioned, scaled and rotated properly.
> Convert Element Usage en Basic Shape

- COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
- COMETwebapp/Components/Viewer/ISceneProvider.cs
- COMETwebapp/Components/Viewer/SceneProvider.cs
- COMETwebapp/Model/OnSelectionChangedEventArgs.cs
- COMETwebapp/Pages/Viewer/ViewerBase.cs
The selection of the primitives now works on both ways:
-Selecting a node in the tree updates the tree view and updates the selection state of the associated primitive.
-Selecting a primitive updates the tree view.
> Selection from both ways

- COMETwebapp.Tests/Viewer/PrimitivesTests.cs
- COMETwebapp/Components/Viewer/SceneProvider.cs
- COMETwebapp/Primitives/BasicPrimitive.cs
- COMETwebapp/Primitives/Cone.cs
- COMETwebapp/Primitives/Cube.cs
- COMETwebapp/Primitives/Cylinder.cs
- COMETwebapp/Primitives/EquilateralTriangle.cs
- COMETwebapp/Primitives/HexagonalPrism.cs
- COMETwebapp/Primitives/Primitive.cs
- COMETwebapp/Primitives/Rectangle.cs
- COMETwebapp/Primitives/ShapeFactory.cs
- COMETwebapp/Primitives/Sphere.cs
- COMETwebapp/Primitives/Torus.cs
- COMETwebapp/Primitives/TriangularPrism.cs
- COMETwebapp/wwwroot/Scripts/babylonInterop.js
The primitives can now be changed at runtime.
> The changes can be applied at runtime

- COMETwebapp.Tests/Viewer/BasicPrimitiveTests.cs
- COMETwebapp.Tests/Viewer/PrimitivesTests.cs
- COMETwebapp/Components/PropertiesPanel/DetailsComponent.razor
- COMETwebapp/Components/PropertiesPanel/DetailsComponent.razor.cs
- COMETwebapp/Components/PropertiesPanel/DetailsComponentBase.cs
- COMETwebapp/Components/PropertiesPanel/Properties.razor.cs
- COMETwebapp/Components/Viewer/BabylonCanvas.razor.cs
- COMETwebapp/Components/Viewer/ISceneProvider.cs
- COMETwebapp/Components/Viewer/SceneProvider.cs
- COMETwebapp/Pages/Viewer/Viewer.razor.cs
- COMETwebapp/Primitives/BasicPrimitive.cs
- COMETwebapp/Primitives/Primitive.cs
- COMETwebapp/wwwroot/Scripts/babylonInterop.js
- COMETwebapp/wwwroot/Scripts/babylonSpecifics.js
The properties now persist on the details panel when another parameter is selected. This makes possible to make all the changes to a primitive and pushed at once.
> Properties now can persist on the details panel

- COMETwebapp.Tests/Components/SubscriptionDashboard/SubscribedTableTestFixture.cs
- COMETwebapp/Components/SubscriptionDashboard/CompoundParameterEvolution.razor
- COMETwebapp/Components/SubscriptionDashboard/CompoundParameterEvolution.razor.cs
- COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor
- COMETwebapp/ViewModels/Components/SubscriptionDashboard/Rows/ParameterSubscriptionRowViewModel.cs
Fix #270 #273 
Parameter Revision Evolution for CompoundParameterTypes : 
- scrollable 
Parameter Revision Evolution for ArrayParameterTypes : 
- 2D example {2;2} : 
- 3D example {3; 2; 2} with tabs to choose wich z coordinate elements to display
> Revisions evolution Compound and Array ParameterTypes : Fix #270 #273 

- COMET.Web.Common.Tests/Utilities/HaveObjectChangedTracking/HaveObjectChangedTrackingTestFixture.cs
- COMET.Web.Common.Tests/ViewModels/Components/SingleIterationApplicationBaseViewModelTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Utilities/HaveObjectChangedTracking/HaveObjectChangedTracking.cs
- COMET.Web.Common/ViewModels/Components/SingleIterationApplicationBaseViewModel.cs
Fix #366 
HaveObjectChangedTracking handles subcriptions for ObjectChangeEvent for specific types
> HaveObjectChangedTracking base class implemented: Fix #366

- COMET.Web.Common/Components/ParameterTypeEditors/TextParameterTypeEditor.razor
Fix #377 
ParameterType name removed from TextParameterTypeEditor to make more room for the input
> Remove parameterType name from TextParameterTypeEditor :  Fix #377

- COMETwebapp/Model/SystemNode.cs
- COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs
Fix #354 
System representation tree is built with all element usage
> Build tree with all element usage : Fix #354

- COMETwebapp/wwwroot/Scripts/babylonInterop.js
Fix #391
All js functions that have await are set to async
> 3D Viewer js file not loaded : Fix #391

- COMETwebapp/Components/ParameterEditor/ParameterTable.razor
- COMETwebapp/ViewModels/Components/ParameterEditor/ParameterTableViewModel.cs
Fix #389 
In ElementDefinition Creation component :
- Categories are ordered by Name,
-  All Categories where the PermissibleClasses does not contains ED are removed
> Element definition creation improvements : Fix #389

- COMET.Web.Common.Tests/Components/ParameterTypeEditors/TextParameterTypeEditorTestFixture.cs
- COMET.Web.Common/Components/ParameterTypeEditors/TextParameterTypeEditor.razor
- COMET.Web.Common/Components/ParameterTypeEditors/TextParameterTypeEditor.razor.cs
- COMET.Web.Common/wwwroot/css/styles.css
Fix #388 
Add a button to open popup to edit TextParameterType using multiline editor.
Make TextBox readoly and add tooltip when hovering on it.
> Multiline editor Text parameter type : Fix #388

- COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs
- COMET.Web.Common.Tests/Components/LoginTestFixture.cs
- COMET.Web.Common.Tests/Components/SingleIterationApplicationTemplateTestFixture.cs
- COMET.Web.Common.Tests/Services/ServerConnectionService/ServerConnectionServiceTestFixture.cs
- COMET.Web.Common.Tests/Services/ServerConnexionService/ServerConnexionServiceTestFixture.cs
- COMET.Web.Common.Tests/ViewModels/Components/SingleIterationApplicationTemplateViewModelTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Components/Login.razor
- COMET.Web.Common/Components/Login.razor.cs
- COMET.Web.Common/Components/SingleIterationApplicationTemplate.razor.cs
- COMET.Web.Common/Extensions/WebAssemblyHostBuilderExtensions.cs
- COMET.Web.Common/Extensions/WebAssemblyHostExtensions.cs
- COMET.Web.Common/Model/GlobalOptions.cs
- COMET.Web.Common/Services/ServerConnectionService/IServerConnectionService.cs
- COMET.Web.Common/Services/ServerConnectionService/ServerConnectionService.cs
- COMET.Web.Common/Services/ServerConnexionService/IServerConnexionService.cs
- COMET.Web.Common/Services/ServerConnexionService/ServerConnexionService.cs
- COMET.Web.Common/ViewModels/Components/ILoginViewModel.cs
- COMET.Web.Common/ViewModels/Components/LoginViewModel.cs
- COMET.Web.Common/wwwroot/server_configuration.json
- COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs
- COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs
- COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs
Fix #424 
Add the possibility to connect to the server using configuration file.
> Common static server address : Fix #424

- .github/workflows/CodeQuality.yml
- README.md
[Remove] Codecov from quality pipeline
> [Remove] Codecov from quality pipeline

- COMET.Web.Common/Components/MultiComboBox.razor
Add a missing namespace to the new MultiComboBox component which was blocking the nuget package from being built.
> Add missing namespace to MultiComboBox component

- COMET.Web.Common.Tests/Components/BookEditor/EditotPopupTestFixture.cs
- COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs
- COMET.Web.Common.Tests/Components/LoginTestFixture.cs
- COMET.Web.Common.Tests/Components/SingleIterationApplicationTemplateTestFixture.cs
- COMET.Web.Common.Tests/Resources/configuration/server_configuration.json
- COMET.Web.Common.Tests/Server/Services/ConfigurationService/ConfigurationServiceTestFixture.cs
- COMET.Web.Common.Tests/WebAssembly/Services/ConfigurationService/ConfigurationServiceTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Components/BookEditor/EditorPopup.razor.cs
- COMET.Web.Common/Components/Login.razor
- COMET.Web.Common/Components/SingleIterationApplicationTemplate.razor.cs
- COMET.Web.Common/Model/Configuration/BookInputConfiguration.cs
- COMET.Web.Common/Model/Configuration/ServerConfiguration.cs
- COMET.Web.Common/Server/Services/ConfigurationService/ConfigurationService.cs
- COMET.Web.Common/Services/ConfigurationService/BaseConfigurationService.cs
- COMET.Web.Common/Services/ConfigurationService/IConfigurationService.cs
- COMET.Web.Common/ViewModels/Components/LoginViewModel.cs
- COMET.Web.Common/WebAssembly/Services/ConfigurationService/ConfigurationService.cs
- COMET.Web.Common/wwwroot/BookInputConfiguration.json
- COMET.Web.Common/wwwroot/server_configuration.json
- COMETwebapp.Tests/Components/BookEditor/BookEditorBodyTestFixture.cs
- COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs
- COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs
- COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs
This change moves the need to use an HttpClient when we're required to access the BookInputConfiguration files.
The changes made here also allow for us to leverage the full power of .NET's IConfiguration implementation and interpret complex JSON objects and not only KeyValuePairs, which allows for some better organization of our setting files.
The changes here affect both WASM and Server modes, where as WASM will read the data from the server_configuration.json file (as it had been doing) and Server should be looking at the appsettings.json file.
> Issue #469 - Move book configuration to the existing ServiceConfiguration

- COMET.Web.Common.Tests/COMET.Web.Common.Tests.csproj
- COMET.Web.Common.Tests/Data/server_configuration_tests.json
- COMET.Web.Common.Tests/Server/Services/ConfigurationService/ConfigurationServiceTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Server/Services/ConfigurationService/ConfigurationService.cs
Essentially, doing a .GetSection() doesn't retrieve the whole object - for that we have to use .Bind() (which I tried at first, but ran into issues while doing unit tests).
For the unit tests to work, a IConfiguration container had to be built, because there's no way to mock the .Bind() method to make it work for tests (it's a static method).
> Fix the way configuration was being bound, to make it work for complex objects.

- COMET.Web.Common.Tests/Shared/TopMenuTestFixture.cs
- COMET.Web.Common/Shared/TopMenu.razor
- COMETwebapp/Program.cs
This will allow us to override the TopMenu component that is rendered on the MainLayout.
> Add the ability to override the TopMenu component on the MainLayout via IOC

- COMET.Web.Common.Tests/Components/LoginTestFixture.cs
- COMET.Web.Common.Tests/Shared/TopMenuTestFixture.cs
- COMET.Web.Common/Components/Login.razor
- COMET.Web.Common/Components/Login.razor.cs
- COMET.Web.Common/Components/MultiComboBox.razor
- COMET.Web.Common/Shared/TopMenu.razor
- COMETwebapp/Program.cs
Fixed [#181](https://gitlab.innovetusa.com/comet/1067/-/issues/181) Gitlab bug
Solved problems with login page: now focused components will not show their error message. BindValueMode updated
> Bug #181 (1067 - Gitlab): login bug

- COMET.Web.Common.Tests/Components/Applications/ApplicationTemplateTestFixture.cs
- COMET.Web.Common/Components/Applications/ApplicationTemplate.razor
- COMET.Web.Common/Components/Applications/ApplicationTemplate.razor.cs
- COMET.Web.Common/Components/Applications/GenericApplicationTemplate.razor
- COMET.Web.Common/Components/Applications/GenericApplicationTemplate.razor.cs
- COMET.Web.Common/Extensions/ServiceCollectionExtensions.cs
- COMET.Web.Common/Extensions/ThingExtensions.cs
Fix #477 
GenericApplicationTemplate created to handle the Generic (required for subcomponent) and implementation of ApplicationTemplate. The ApplicationTemplate can be used now.
Cleanup encoding and tab for ThingExtension file
> Fix #477- ApplicationTemplate can be used as is

- COMET.Web.Common/Utilities/CherryPick/CherryPickRunner.cs
We were using the SetupIds instead of the Model/Iteration Ids.
> Fix the CherryPickRunner to use the correct Iids

- COMET.Web.Common/ViewModels/Components/Applications/ApplicationBaseViewModel.cs
- COMETwebapp.Tests/ViewModels/Components/ParameterEditor/ParameterEditorBodyViewModelTestFixture.cs
Filter EndUpdate event subscriptions for the same Session
> Fix Loading Bug on program manager dashboard

- COMET.Web.Common.Tests/Extensions/SessionServiceExtensionsTestFixture.cs
- COMET.Web.Common.Tests/Services/SessionManagement/SessionServiceTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Extensions/SessionServiceExtensions.cs
- COMET.Web.Common/Services/SessionManagement/ISessionService.cs
- COMET.Web.Common/Services/SessionManagement/SessionService.cs
- COMETwebapp.Tests/Components/SystemRepresentation/SystemRepresentationBodyTestFixture.cs
This PR includes some improvements for the ISessionService. This will fix #489
> Feat/SessionServiceImprovements. Fix #489

- COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs
Fix #491
- SelectedIterationSetup correctly preset. Not possible to have it preset with an open iteration anymore
> Fix #491: SelectedIterationSetup correctly set

- .dockerignore
- .gitignore
- COMET.Web.Common.Tests/Components/Applications/SingleEngineeringModelApplicationTemplateTestFixture.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Components/Applications/SingleEngineeringModelApplicationTemplate.razor
- COMET.Web.Common/Components/Applications/SingleEngineeringModelApplicationTemplate.razor.cs
- COMET.Web.Common/Components/Applications/SingleIterationApplicationTemplate.razor.cs
- COMET.Web.Common/ViewModels/Components/Applications/SingleIterationApplicationTemplateViewModel.cs
- COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs
- COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs
- COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs
- COMETwebapp.sln.DotSettings
> Fix #475: Added EngineeringModelId inside Template and improvement

- COMET.Web.Common.Tests/Utilities/HaveObjectChangedTracking/HaveObjectChangedTrackingTestFixture.cs
- COMET.Web.Common.Tests/ViewModels/Components/Applications/SingleIterationApplicationBaseViewModelTestFixture.cs
- COMET.Web.Common/Utilities/HaveObjectChangedTracking/HaveObjectChangedTracking.cs
In HaveObjectChangedTracking  class:
- Exposes IReadOnlyCollection
- Exposes ClearRecordedChanges method
> Exposing IReadOnlyCollection for tracked Things

- COMET.Web.Common/Components/ParameterTypeEditors/TextParameterTypeEditor.razor
- COMET.Web.Common/Components/Tooltip.razor
- COMET.Web.Common/Components/Tooltip.razor.cs
- COMET.Web.Common/wwwroot/css/styles.css
- COMETwebapp/Components/ParameterEditor/ParameterTable.razor
…p improvement
Closes #523 [Parameter Editor] when the user clicks on the "Add an ElementDefinition" button an unhandled error occurs #523
- Removes "add an element definition" button from parameter editor
- Tooltip improvements
> Fix #523 "Add an ElementDefinition" button error in parameter editor + tooltip improvements

- COMET.Web.Common/ViewModels/Components/Applications/ApplicationBaseViewModel.cs
- COMET.Web.Common/ViewModels/Components/Applications/IHaveReusableRows.cs
- COMETwebapp/ViewModels/Components/ParameterEditor/IParameterTableViewModel.cs
- COMETwebapp/ViewModels/Components/ParameterEditor/ParameterEditorBodyViewModel.cs
Closes #476 IHaveReusableRows for VM that can recycle their rows 
- A new IHaveReusableRows has been introduced for viewmodels that need to recycle their rows
- The application base view model class has now the method "UpdateInnerComponents", that calls the methods AddRows, UpdateRows and RemoveRows from the registered viewmodels in the collection RegisteredViewModelsWithReusableRows
> Feat #476 IHaveReusableRows interface introduced

- COMET.Web.Common/Components/Applications/SingleEngineeringModelApplicationTemplate.razor.cs
- COMETwebapp.Tests/Components/BookEditor/BookEditorBodyTestFixture.cs
- COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/BookEditor/BookEditorBodyViewModelTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModelTestFixture.cs
- COMETwebapp/Components/BookEditor/BookEditorBody.razor
- COMETwebapp/Components/UserManagement/UserManagementTable.razor
- COMETwebapp/Pages/BookEditor/BookEditor.razor
- COMETwebapp/Pages/UserManagement/UserManagementPage.razor
- COMETwebapp/ViewModels/Components/BookEditor/BookEditorBodyViewModel.cs
- COMETwebapp/ViewModels/Components/BookEditor/IBookEditorBodyViewModel.cs
- COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
- COMETwebapp/ViewModels/Components/ModelEditor/IElementDefinitionTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/CategoriesTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/ICategoriesTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/IParameterTypeTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/ParameterTypeTableViewModel.cs
- COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs
- COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Closes #474 Refactor applications based on new components
- Now components that dont need iteration data inherit either ApplicationBaseViewModel or SingleEngineeringModelApplicationBaseViewModel
- Fixed null CurrentThing for SingleEngineeringModelApplicationBaseViewModel
- Also, some refactor was done to include IHaveReusableRows in applications
> Feat #474 Refactor applications based on new components

- COMETwebapp.Tests/Components/ReferenceData/MeasurementUnitsTableTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementUnitsTableViewModelTestFixture.cs
- COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor
- COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor.cs
- COMETwebapp/Extensions/ServiceCollectionExtensions.cs
- COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor
- COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor.cs
- COMETwebapp/ViewModels/Components/ReferenceData/IMeasurementUnitsTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/MeasurementUnitsTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/Rows/MeasurementUnitRowViewModel.cs
- WebAppHeader.DotSettings
Closes #536 [Reference Data] Measurement Units - display
- Added deprecate/undeprecate functionalities
- Table rows are reactive to session events
- Placeholders created for further create/edit features
> Feat #536 [Reference Data] Measurement Units - display

- COMETwebapp.Tests/Components/ReferenceData/MeasurementScalesTableTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementScalesTableViewModelTestFixture.cs
- COMETwebapp/Components/ReferenceData/MeasurementScalesTable.razor
- COMETwebapp/Components/ReferenceData/MeasurementScalesTable.razor.cs
- COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor
- COMETwebapp/Extensions/ServiceCollectionExtensions.cs
- COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor
- COMETwebapp/ViewModels/Components/ReferenceData/IMeasurementScalesTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScalesTableViewModel.cs
- COMETwebapp/ViewModels/Components/ReferenceData/Rows/MeasurementScaleRowViewModel.cs
- layout for create/edit implemented
- unit tests done
Closes #542 [Reference Data] Measurement Scales - display #542
- Added deprecate/undeprecate functionalities
- Table rows are reactive to session events
- Placeholders created for further create/edit features
> Feat #542 [Reference Data] Measurement Scales - display

- COMETwebapp.Tests/Components/ReferenceData/ParameterTypes/ParameterTypeTableTestFixture.cs
- COMETwebapp/Components/Common/DataItemDetailsComponent.razor
- COMETwebapp/Components/Common/DataItemDetailsComponent.razor.cs
- COMETwebapp/Components/Common/SelectedDataItemForm.razor.cs
- COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesForm.razor
- COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor
- COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeForm.razor
- COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeTable.razor
- COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeTable.razor.cs
Closes #604 [Reference Data] refactor ParameterTypes page to be inline with measurement scales page
> Feat #604 [Reference Data] refactor ParameterTypes page to be inline with measurement scales page

- COMETwebapp/ViewModels/Components/Common/DeletableDataItemTable/DeletableDataItemTableViewModel.cs
Closes #616 CommonFileStore: when a user adds a filestore and then tries to delete the filestore the application crashes
> Fix #616 CommonFileStore: when a user adds a filestore and then tries to delete the filestore the application crashes

- COMET.Web.Common.Tests/Components/Applications/DynamicApplicationBaseTestFixture.cs
- COMET.Web.Common/Components/Applications/ApplicationBase.razor.cs
- COMET.Web.Common/Components/Applications/DynamicApplicationBase.razor
- COMET.Web.Common/Components/Applications/DynamicApplicationBase.razor.cs
- COMET.Web.Common/Components/Applications/SingleThingApplicationBase.razor.cs
- COMET.Web.Common/Utilities/TypeChecker.cs
- COMETwebapp.Tests/Components/SubscriptionDashboard/SubscriptionDashboardBodyTestFixture.cs
- COMETwebapp.Tests/Model/ApplicationsTestFixture.cs
- COMETwebapp.Tests/Pages/TabsViewModelTestFixture.cs
- COMETwebapp.sln.DotSettings
- COMETwebapp/Components/BookEditor/BookEditorBody.razor.cs
- COMETwebapp/Components/EngineeringModel/EngineeringModelBody.razor.cs
- COMETwebapp/Components/ModelDashboard/ModelDashboardBody.razor.cs
- COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor.cs
- COMETwebapp/Components/ParameterEditor/ParameterEditorBody.razor.cs
- COMETwebapp/Components/SubscriptionDashboard/SubscriptionDashboardBody.razor.cs
- COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.cs
- COMETwebapp/Components/Viewer/ViewerBody.razor.cs
- COMETwebapp/Extensions/ServiceCollectionExtensions.cs
- COMETwebapp/Model/Applications.cs
- COMETwebapp/Model/TabbedApplication.cs
- COMETwebapp/Model/TabbedApplicationInformation.cs
- COMETwebapp/Pages/Tabs.razor
- COMETwebapp/Pages/Tabs.razor.cs
- COMETwebapp/Utilities/WebAppConstantValues.cs
- COMETwebapp/ViewModels/Pages/ITabsViewModel.cs
- COMETwebapp/ViewModels/Pages/TabsViewModel.cs
- CommonLibrary.DotSettings
- WebAppHeader.DotSettings
Fix #656 #661 #662 
- ApplicationBase components also supports to have the ViewModel set via Parameter
- DynamicApplicationBase component support to render any ApplicationBase with the associated ViewModel
- Tabs page implemented to support the core: For now, possible to select the Application to show via a dropdown
> Fix #656 #661 #662: Core components implemented for tab flow

- COMETwebapp.Tests/ViewModels/Components/ParameterEditor/ParameterEditorBodyViewModelTestFixture.cs
- COMETwebapp.Tests/ViewModels/Pages/TabsViewModelTestFixture.cs
- COMETwebapp/ViewModels/Pages/TabsViewModel.cs
Closes #685 fix open tabs bug after closing session
Additionally, this PR also solves:
- an error thrown when an iteration opened in two or more tabs, in the same application, was closed.
- engineering model tabs not closing when the users logs out
> Fix #685 fix open tabs bug after closing session

- COMETwebapp/Components/Common/SelectedDataItemForm.razor.cs
- COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeForm.razor.cs
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor
- COMETwebapp/Validators/ReferenceData/ParameterTypes/GenericValidators/ParameterQuantityKindValidator.cs
Closes #694 [Reference Data] Parameter types - UI problems
Closes #696 Change "tab" text from "open model" to "Select Model"
> Fix #694 [Reference Data] Parameter types - UI problems + #696 Tab text update

- COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs
- COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs
- COMETwebapp.Tests/Pages/TabsTestFixture.cs
- COMETwebapp/Components/Tabs/OpenTab.razor
- COMETwebapp/Components/Tabs/TabComponent.razor
- COMETwebapp/Components/Tabs/TabComponent.razor.cs
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor.cs
- COMETwebapp/Pages/Tabs.razor
- COMETwebapp/Pages/Tabs.razor.cs
Closes #697 From a tab, allow a user to open a new tab by only selecting the view of interest
Screenshots
> Feat #697 From a tab, allow a user to open a new tab by only selecting the view of interest

- COMETwebapp.Tests/Components/Tabs/TabsPanelComponentTestFixture.cs
- COMETwebapp.Tests/Pages/TabsTestFixture.cs
- COMETwebapp/Components/Tabs/TabComponent.razor
- COMETwebapp/Components/Tabs/TabComponent.razor.cs
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor.cs
Closes #698 Update tab caption
Screenshot below
> Feat #698 Update tab caption

- COMETwebapp/Components/Common/DataItemDetailsComponent.razor
- COMETwebapp/Components/Common/DataItemDetailsComponent.razor.cs
- COMETwebapp/Components/Common/DataItemDetailsComponent.razor.css
- COMETwebapp/Components/EngineeringModel/CommonFileStoresTable.razor
- COMETwebapp/Components/EngineeringModel/DomainFileStore/DomainFileStoresTable.razor
- COMETwebapp/Components/EngineeringModel/OptionsTable.razor
- COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor
- COMETwebapp/Components/ParameterEditor/ParameterTable.razor.css
- COMETwebapp/Components/ReferenceData/Categories/CategoriesTable.razor
- COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor
- COMETwebapp/Components/ReferenceData/MeasurementUnits/MeasurementUnitsTable.razor
- COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeTable.razor
- COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseTable.razor
- COMETwebapp/Components/SiteDirectory/EngineeringModel/EngineeringModelsTable.razor
- COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor
- COMETwebapp/Components/SiteDirectory/Roles/ParticipantRolesTable.razor
- COMETwebapp/Components/SiteDirectory/Roles/PersonRolesTable.razor
- COMETwebapp/Components/SiteDirectory/UserManagement/UserManagementTable.razor
- COMETwebapp/Components/Tabs/TabsPanelComponent.razor.css
- COMETwebapp/Pages/_Host.cshtml
- COMETwebapp/ViewModels/Components/SiteDirectory/EngineeringModels/EngineeringModelsTableViewModel.cs
- COMETwebapp/wwwroot/css/app.css
Closes #702 Reduce the need to horizontally scroll when split screen is applied => Now pages are responsive
- Additionally, a bug in model updates was solved
> Feat #702 Reduce the need to horizontally scroll when split screen is applied 

- COMET.Web.Common/Components/Selectors/DomainOfExpertiseSelector.razor
- COMET.Web.Common/ViewModels/Components/Selectors/DomainOfExpertiseSelectorViewModel.cs
- COMET.Web.Common/ViewModels/Components/Selectors/IDomainOfExpertiseSelectorViewModel.cs
- COMETwebapp.Tests/Components/ParameterEditor/BatchParameterEditorTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/ParameterEditor/BatchParameterEditorViewModelTestFixture.cs
- COMETwebapp/Components/ParameterEditor/BatchParameterEditor/BatchParameterEditor.razor
- COMETwebapp/Components/ParameterEditor/BatchParameterEditor/BatchParameterEditor.razor.cs
- COMETwebapp/ViewModels/Components/ParameterEditor/BatchParameterEditor/BatchParameterEditorViewModel.cs
- COMETwebapp/ViewModels/Components/ParameterEditor/BatchParameterEditor/IBatchParameterEditorViewModel.cs
Closes #596 [Parameter Editor] Allow parameter filtering by category and domains of expertise in batch update
Screenshot
> Feat #596 [Parameter Editor] Allow parameter filtering by category and domains of expertise in batch update

- COMETwebapp.Tests/Components/Viewer/PropertiesPanel/PropertiesComponentTestFixture.cs
- COMETwebapp/Components/ParameterEditor/ParameterTable.razor
- COMETwebapp/Components/Viewer/PropertiesPanel/PropertiesComponent.razor
- COMETwebapp/Components/Viewer/PropertiesPanel/PropertiesComponent.razor.cs
- COMETwebapp/Components/Viewer/ViewerBody.razor.css
- COMETwebapp/ViewModels/Components/Viewer/ViewerProductTreeViewModel.cs
Closes #430 [Parameter Editor] Both parameter values and parameter overrides are shown with no clear distinction 
Closes #347 [3D Viewer] improvements on spacing and parameter editor
> Fix #430 Parameter overrides are shown with no clear distinction & Fix #347 [3D Viewer] Improvements on spacing and parameter editor

- COMET.Web.Common.Test/COMET.Web.Common.Test.csproj
- COMET.Web.Common.Tests/COMET.Web.Common.Tests.csproj
- COMET.Web.Common/COMET.Web.Common.csproj
- COMETwebapp.Tests/COMETwebapp.Tests.csproj
- COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs
- COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs
- COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs
- COMETwebapp.Tests/ViewModels/Components/ParameterEditor/ParameterTableViewModelTestFixture.cs
- COMETwebapp/COMETwebapp.csproj
- COMETwebapp/Components/ParameterEditor/ParameterTable.razor
- COMETwebapp/ViewModels/Components/ParameterEditor/ParameterBaseRowViewModel.cs
Add ParameterGroup path to ParameterEditor.
> Add ParameterGroupName to ParameterEditor; fixes #720

- .github/workflows/CodeQuality.yml
- .github/workflows/codeql.yml
- .github/workflows/nuget-reference-check.yml
- COMET.Web.Common.Test/COMET.Web.Common.Test.csproj
- COMET.Web.Common.Tests/COMET.Web.Common.Tests.csproj
- COMET.Web.Common.Tests/Components/LoginTestFixture.cs
- COMET.Web.Common.Tests/Extensions/ServiceCollectionExtensionsTestFixture.cs
- COMET.Web.Common.Tests/Pages/CallbackTestFixture.cs
- COMET.Web.Common.Tests/Services/SessionManagement/AuthenticationServiceTestFixture.cs
- COMET.Web.Common.Tests/ViewModels/Components/LoginViewModelTestFixture.cs
- COMET.Web.Common/App.razor.cs
- COMET.Web.Common/COMET.Web.Common.csproj
- COMET.Web.Common/Components/Login.razor
- COMET.Web.Common/Components/Login.razor.cs
- COMET.Web.Common/Extensions/ServiceCollectionExtensions.cs
- COMET.Web.Common/Model/Configuration/ServerConfiguration.cs
- COMET.Web.Common/Model/DTO/AuthenticationDto.cs
- COMET.Web.Common/Model/DTO/OpenIdAuthenticationDto.cs
- COMET.Web.Common/Pages/Callback.razor
- COMET.Web.Common/Pages/Callback.razor.cs
- COMET.Web.Common/Services/SessionManagement/AuthenticationService.cs
- COMET.Web.Common/Services/SessionManagement/IAuthenticationService.cs
- COMET.Web.Common/Validators/AuthenticationDtoValidator.cs
- COMET.Web.Common/ViewModels/Components/ILoginViewModel.cs
- COMET.Web.Common/ViewModels/Components/LoginViewModel.cs
- COMETwebapp.Tests/COMETwebapp.Tests.csproj
- COMETwebapp.Tests/Pages/IndexTestFixture.cs
- COMETwebapp/COMETwebapp.csproj
- COMETwebapp/Dockerfile
- COMETwebapp/appsettings.Development.json
COMET.Web.Common provides core implementation to allow JWT-based authentication.
The COMET-WebApp can be parameterized to allow or not the multi-scheme authentication flow. Login component (in COMET.Web.Common) provides flexible UI that allow support of all authentication scheme.
Callback page implemented to handle an OpenID redirection flow.
> Support JWT authentication, including multi-steps authentication
