STARIONGROUP/COMET-WEB-Community-Edition

.github/workflows/codeql.yml, COMETwebapp/Components/OpenModel.razor, COMETwebapp/Model/ApplicationCards.cs, COMETwebapp/Pages/Model.razor, COMETwebapp/Shared/NavMenu.razor, COMETwebapp/Shared/NavMenu.razor.css, COMETwebapp/wwwroot/css/app.css
Add links for applications in the sidebar.
=> Add links in NavMenu; fixes #14

COMETwebapp.Tests/Utilities/GuidExtensionsTestFixture.cs, COMETwebapp/Utilities/GuidExtensions.cs, COMETwebapp/Utilities/StringExtensions.cs
extensions methods usefull to shorten guids and encode strings for use in urls and queryparameters
=> [Add] utility methods to encode/decode strings and guids

COMETwebapp/Components/ModelDashboard/Dashboard.razor, COMETwebapp/Components/ModelDashboard/DefaultValues.razor, COMETwebapp/Components/ModelDashboard/DonutDashboard.razor, COMETwebapp/Components/ModelDashboard/PublishedParameters.razor, COMETwebapp/wwwroot/css/app.css
Adapt layout depending on the page size.
I put the css on the general css page but maybe for this type of code, we should use css isolation (with .razor.css file) for a better understanding and faster change ?
=> Add adapting layout; fixes 63

COMETwebapp/Components/ApplicationTemplate.razor, COMETwebapp/Components/ModelDashboard/DonutDashboard.razor, COMETwebapp/Components/ModelDashboard/ElementDashboard.razor, COMETwebapp/Components/ModelDashboard/ParameterDashboard.razor, COMETwebapp/Components/ModelDashboard/UnreferencedElements.razor, COMETwebapp/Components/ModelDashboard/UnusedElements.razor, COMETwebapp/Components/ParameterTable.razor, COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor, COMETwebapp/IterationServices/IIterationService.cs, COMETwebapp/IterationServices/IterationService.cs, COMETwebapp/Pages/ModelDashboard/DataDetails.razor, COMETwebapp/Pages/ModelDashboard/ElementsDetails.razor, COMETwebapp/Pages/ModelDashboard/ModelDashboard.razor, COMETwebapp/Pages/Settings.razor, COMETwebapp/SessionManagement/ISessionAnchor.cs, COMETwebapp/SessionManagement/SessionAnchor.cs, COMETwebapp/Shared/Header.razor, COMETwebapp/Shared/NavMenu.razor
- Add feature to be able to switch domain in the application.
- Add correction in use of CDPMessageBus listeners => improve delays in session refresh
=> Add switch domain feature; fixes #74

COMETwebapp.Tests/COMETwebapp.Tests.csproj, COMETwebapp.Tests/Shared/HeaderTestFixture.cs, COMETwebapp/Shared/Header.razor
a bUnit test that demonstrates how a component can be tested and how injected services can be tested such as the `ISessionAnchor` without need to have a connection to a live server
=> [Add] bUnit test for Header component

COMETwebapp.Tests/SessionManagement/CometWebAuthStateProviderTestFixture.cs, COMETwebapp/SessionManagement/AuthenticationService.cs, COMETwebapp/SessionManagement/CometWebAuthStateProvider.cs
[Improve] code coverage for CometWebAuthStateProvider
=> [Improve] code coverage for CometWebAuthStateProvider

COMETwebapp/Pages/ModelDashboard/ModelDashboard.razor
Change select component to be able to write the name, and order the list in alphabetic order.
Change for option, state and parameter type.
fixes #112
=> Change select component; fixes #112

COMETwebapp/Components/ParameterEditor/ParameterTree.razor, COMETwebapp/Components/ParameterEditor/ParameterTreeNode.razor, COMETwebapp/Pages/ParameterEditor/ParameterEditor.razor
Add a filter on parameter type.
fixes #20
=> Add filter on parameter type; fixes #20

COMETwebapp/Components/ParameterEditor/ParameterTreeNode.razor, COMETwebapp/Components/ParameterEditor/ParameterValueSetRow.razor, COMETwebapp/Components/ParameterValueSetRender/ScalarParameter.razor
When you edit a value, actual value is also updated with the new value when it's needed.
fixes #127
=> Updates actual value with changes; fixes #127

COMETwebapp.Tests/Viewer/PrimitivesTests.cs, COMETwebapp/Components/PropertiesPanel/Properties.razor, COMETwebapp/Components/PropertiesPanel/PropertiesBase.cs, COMETwebapp/Components/PropertiesPanel/Transformation.razor, COMETwebapp/Components/PropertiesPanel/TransformationBase.cs, COMETwebapp/Components/Viewer/BabylonCanvasBase.cs, COMETwebapp/Components/Viewer/ISceneProvider.cs, COMETwebapp/Components/Viewer/SceneProvider.cs, COMETwebapp/Pages/Viewer/Viewer.razor, COMETwebapp/Pages/Viewer/ViewerBase.cs, COMETwebapp/Primitives/BasicPrimitive.cs, COMETwebapp/Primitives/Cone.cs, COMETwebapp/Primitives/Cube.cs, COMETwebapp/Primitives/Cylinder.cs, COMETwebapp/Primitives/Disc.cs, COMETwebapp/Primitives/EquilateralTriangle.cs, COMETwebapp/Primitives/HexagonalPrism.cs, COMETwebapp/Primitives/Primitive.cs, COMETwebapp/Primitives/Rectangle.cs, COMETwebapp/Primitives/ShapeFactory.cs, COMETwebapp/Primitives/Sphere.cs, COMETwebapp/Primitives/Torus.cs, COMETwebapp/Primitives/TriangularPrism.cs, COMETwebapp/wwwroot/Scripts/babylonInterop.js, COMETwebapp/wwwroot/Scripts/babylonSpecifics.js
When a primitive is selected a panel with some properties is shown.
=> Show a Properties panel for the selected primitive

COMETwebapp/Components/PropertiesPanel/Properties.razor, COMETwebapp/Primitives/Primitive.cs
Now the changes made in the UI can be pushed to the server
=> Changes can be pushed to source

COMETwebapp.Tests/Viewer/MatrixExtensionsTests.cs, COMETwebapp/Components/PropertiesPanel/DetailsComponent.razor, COMETwebapp/Components/PropertiesPanel/DetailsComponentBase.cs, COMETwebapp/Components/PropertiesPanel/Orientation.razor, COMETwebapp/Components/PropertiesPanel/Orientation.razor.cs, COMETwebapp/Components/PropertiesPanel/Orientation.razor.css, COMETwebapp/Primitives/BasicPrimitive.cs, COMETwebapp/Utilities/IValueSetExtensions.cs, COMETwebapp/Utilities/MatrixExtensions.cs
The rotations can be performed by the Euler angles. In the code behind the use it's still the rotation matrix. And the information saved in the server is the rotation matrix.
=> Rotations can be performed by Euler Angles

COMETwebapp.Tests/Components/ReferenceData/ParameterTypeTableTestFixture.cs, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor.cs, COMETwebapp/Model/ApplicationCards.cs, COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor, COMETwebapp/Program.cs, COMETwebapp/ViewModels/Components/ReferenceData/IParameterTypeTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ParameterTypeTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/Rows/ParameterTypeRowViewModel.cs, COMETwebapp/wwwroot/css/app.css, COMETwebapp/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
Fix #268 
Feature :
- A user can see all available parameter types
- Filter, sort and search for a prameter type
=> Parameter type representation : Fix #268

COMETwebapp.Tests/Components/ReferenceData/CategoriesTableTestFixture.cs, COMETwebapp/Components/ReferenceData/CategoriesTable.razor, COMETwebapp/Components/ReferenceData/CategoriesTable.razor.cs, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/Extensions/EnumerableExtensions.cs, COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor, COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor.cs, COMETwebapp/Program.cs, COMETwebapp/ViewModels/Components/ReferenceData/CategoriesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ICategoriesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/Rows/CategoryRowViewModel.cs
Fix #269 
Feature :
A user can see all available categories
Filter, sort and search for a categories
=> Categories representation : Fix #269

COMETwebapp.Tests/Components/ReferenceData/CategoriesTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/ParameterTypeTableTestFixture.cs, COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs, COMETwebapp/Components/ReferenceData/CategoriesTable.razor, COMETwebapp/Components/ReferenceData/CategoriesTable.razor.cs, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/ViewModels/Components/ReferenceData/CategoriesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ICategoriesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/IParameterTypeTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ParameterTypeTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Fix #281 
Prevent users who don't have access right to write a Thing
Handle the update of a person role on session refresh
=> User access write to update ot create Thing : Fix #281

COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/Rows/PersonRowViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Fix #297 
- The deprecated items are hidden by default
- Fix the role column to provide the name of the Person Role
- The current user is not allowed to de-active himself
- The current user is not allowed to deprecate himself
=>  User management improvements : Fix #297

COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/EnumerationParameterTypeEditorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/EnumerationParameterTypeEditorViewModelTestFixture.cs, COMETwebapp/Components/Shared/ParameterTypeEditors/EnumerationParameterTypeEditor.razor, COMETwebapp/Components/Shared/ParameterTypeEditors/EnumerationParameterTypeEditor.razor.cs, COMETwebapp/ViewModels/Components/Shared/ParameterEditors/EnumerationParameterTypeEditorViewModel.cs, COMETwebapp/ViewModels/Components/Shared/ParameterEditors/IEnumerationParameterTypeEditorViewModel.cs, COMETwebapp/wwwroot/css/app.css
Fix #282 
For EnumerationParameterType that allows multi-selection :
- The UI shows a dropdown component with a ListBox to select multiple elements
- Write selected values to database
=> Multiple value selection for enumeration : Fix #282

COMETwebapp.Tests/Components/ParameterEditor/ParameterEditorBodyTestFixture.cs, COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/QuantityKindParameterTypeEditorTestFixture.cs, COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ParameterEditor/ParameterTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterEditorBodyViewModelTestFixture.cs, COMETwebapp/Components/ParameterEditor/ParameterEditorBody.razor, COMETwebapp/Components/ParameterEditor/ParameterTable.razor, COMETwebapp/Components/ParameterEditor/ParameterTable.razor.cs, COMETwebapp/Components/Shared/ParameterTypeEditors/QuantityKindParameterTypeEditor.razor, COMETwebapp/Components/Shared/ParameterTypeEditors/QuantityKindParameterTypeEditor.razor.css, COMETwebapp/Components/Shared/Selectors/OptionSelector.razor, COMETwebapp/Extensions/ThingExtensions.cs, COMETwebapp/ViewModels/Components/ParameterEditor/IParameterBaseRowViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/IParameterEditorBodyViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/IParameterTableViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterBaseRowViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterEditorBodyViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterTableViewModel.cs, COMETwebapp/ViewModels/Components/Shared/ParameterEditors/IParameterEditorBaseViewModel.cs, COMETwebapp/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorBaseViewModel.cs, COMETwebapp/ViewModels/Components/Shared/Selectors/ElementBaseSelectorViewModel.cs, COMETwebapp/ViewModels/Components/Shared/Selectors/IOptionSelectorViewModel.cs, COMETwebapp/ViewModels/Components/Shared/Selectors/OptionSelectorViewModel.cs
Fix #310 #296
- Filtering is done as described in #310 
- Add MeasurementScale when applicable
=> Filtering improvement and add missing Measurementscale: Fix #310 #296

COMETwebapp.Tests/Pages/LogoutTestFixture.cs, COMETwebapp.Tests/Shared/TopMenuTestFixture.cs, COMETwebapp/Pages/Logout.razor, COMETwebapp/Pages/Logout.razor.cs, COMETwebapp/Shared/TopMenuEntry/SessionMenu.razor.cs, COMETwebapp/ViewModels/Shared/TopMenuEntry/ISessionMenuViewModel.cs, COMETwebapp/ViewModels/Shared/TopMenuEntry/SessionMenuViewModel.cs
Fix #318 
- Logout page enables to properly logout
=> Logout page implemented: Fix #318

COMETwebapp/Components/ModelDashboard/ParameterValues/DonutDashboard.razor
Fix #321
Obsolete DxChartDonutSeries  have been replaced by DxPieChartSeries
=> Replace DxChartDonutSeries by DxPieChartSeries : Fix #321

COMETwebapp.Tests/Components/SubscriptionDashboard/SubscribedTableTestFixture.cs, COMETwebapp/Components/SubscriptionDashboard/BooleanParameterEvolution.razor, COMETwebapp/Components/SubscriptionDashboard/BooleanParameterEvolution.razor.cs, COMETwebapp/Components/SubscriptionDashboard/EnumerationParameterEvolution.razor, COMETwebapp/Components/SubscriptionDashboard/EnumerationParameterEvolution.razor.cs, COMETwebapp/Components/SubscriptionDashboard/ParameterEvolutionSelector.razor, COMETwebapp/Components/SubscriptionDashboard/ParameterEvolutionSelector.razor.cs, COMETwebapp/Components/SubscriptionDashboard/SubscribedParameterEvolution.razor, COMETwebapp/Components/SubscriptionDashboard/SubscribedParameterEvolution.razor.cs, COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor, COMETwebapp/Model/RevisionHistory.cs
Fix #272 #271 
The evolution graph supports : 
- BooleanParameterType
- EnumerationParamerType
- EnumerationParamerType  that allows multiple selection :
=> Revisions evolution boolean and enumeration ParameterTypes : Fix #272 #271

COMETwebapp.Tests/Components/SubscriptionDashboard/SubscribedTableTestFixture.cs, COMETwebapp/Components/SubscriptionDashboard/DateParameterEvolution.razor, COMETwebapp/Components/SubscriptionDashboard/DateParameterEvolution.razor.cs, COMETwebapp/Components/SubscriptionDashboard/ParameterEvolutionSelector.razor
Fix #329 
Parameter Revision Evolution for DateParameterType:
Parameter Revision Evolution for DateTimeParameterType:
=> Revisions evolution date and datetime ParameterTypes : Fix #329

COMETwebapp.Tests/Components/SystemRepresentation/SystemRepresentationBodyTestFixture.cs, COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor, COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/ISystemRepresentationBodyViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs
Fix #307 
- The SystemRepresentation uses common components created for filtering. 
- When selecting option filter, the selection is reflected inside the URL
=> System representation common component and url update : Fix #307

COMETwebapp.Tests/Components/ParameterEditor/ParameterEditorBodyTestFixture.cs, COMETwebapp.Tests/Components/ParameterEditor/ParameterTableTestFixture.cs, COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ParameterEditor/ParameterTableViewModelTestFixture.cs, COMETwebapp/Components/ParameterEditor/ParameterTable.razor, COMETwebapp/Components/ParameterEditor/ParameterTable.razor.cs, COMETwebapp/ViewModels/Components/ParameterEditor/IParameterTableViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterTableViewModel.cs, COMETwebapp/wwwroot/css/app.css
Fix #23 
A user can create a new ElementDefinition
=> [Parameter editor] Element Definition Creation : Fix #23

COMETwebapp.Tests/Components/Viewer/PropertiesPanel/PropertiesComponentTestFixture.cs, COMETwebapp/ViewModels/Components/Viewer/PropertiesPanel/PropertiesComponentViewModel.cs
Fix #350 
The CompoundParameterType changes are not blocking the element scene update
=> Element scene properties update for CompoundParameterTypes : Fix #350

COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs, COMET.Web.Common.Tests/Components/OpenModelTestFixture.cs, COMET.Web.Common.Tests/Components/SingleIterationApplicationTemplateTestFixture.cs, COMET.Web.Common.Tests/Services/ConfigurationService/ConfigurationServiceTestFixture.cs, COMET.Web.Common/App.razor.cs, COMET.Web.Common/COMET.Web.Common.csproj, COMET.Web.Common/Components/OpenModel.razor, COMET.Web.Common/Components/OpenModel.razor.cs, COMET.Web.Common/Enumerations/TextConfigurationKind.cs, COMET.Web.Common/Extensions/WebAssemblyHostBuilderExtensions.cs, COMET.Web.Common/Extensions/WebAssemblyHostExtensions.cs, COMET.Web.Common/Model/GlobalOptions.cs, COMET.Web.Common/Services/ConfigurationService/ConfigurationService.cs, COMET.Web.Common/Services/ConfigurationService/IConfigurationService.cs, COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs, COMET.Web.Common/wwwroot/DefaultTextConfiguration.json, COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs, COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs, COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs, COMETwebapp/COMETwebapp.csproj, COMETwebapp/Program.cs
- Creation of Configuration Service
- The OpenModel popup selects the Iteration and the Domain of Expertise when the model is selected.
=> Add Configuration Service

COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs, COMET.Web.Common.Tests/Components/ParameterTypeEditors/CompoundParameterTypeEditorTestFixture.cs, COMET.Web.Common/Components/DisposableComponent.razor.cs, COMET.Web.Common/Shared/TopMenuEntry/MenuEntryBase.razor, COMET.Web.Common/Shared/TopMenuEntry/MenuEntryBase.razor.cs, COMETwebapp.Tests/Components/ReferenceData/CategoriesTableTestFixture.cs, COMETwebapp.Tests/Components/SystemRepresentation/SystemRepresentationBodyTestFixture.cs, COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs, COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs, COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs, COMETwebapp/COMETwebapp.csproj, COMETwebapp/Components/ModelDashboard/Elements/HaveElementDefinitionData.razor.cs, COMETwebapp/Components/ModelDashboard/HaveChartData.razor.cs, COMETwebapp/Components/ModelDashboard/ParameterValues/HaveValueSetsChartData.razor.cs, COMETwebapp/Components/ModelDashboard/ParameterValues/PublishedParameters.razor.cs, COMETwebapp/Components/SystemRepresentation/ElementDefinitionDetails.razor, COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.css, COMETwebapp/Components/SystemRepresentation/SystemTree.razor, COMETwebapp/Components/SystemRepresentation/SystemTree.razor.css, COMETwebapp/ViewModels/Components/SystemRepresentation/ElementDefinitionDetailsViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/IElementDefinitionDetailsViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/ISystemRepresentationBodyViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/Rows/ElementDefinitionDetailsRowViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs
Fix #348 #374 
- Remove the spacing between the tree and the details panel.
- Rename the title of the details panels states to "Building Block"
=> System representation improvements : Fix #348

COMET.Web.Common/Components/ApplicationCard.razor, COMET.Web.Common/wwwroot/css/styles.css
Fix #382 
CSS for the ApplicationCard has been fixed
=> ApplicationCard css fixed: Fix #382

COMET.Web.Common.Tests/Services/RegistrationService/RegistrationServiceTestFixture.cs, COMET.Web.Common/App.razor, COMET.Web.Common/Model/GlobalOptions.cs, COMET.Web.Common/Services/RegistrationService/IRegistrationService.cs, COMET.Web.Common/Services/RegistrationService/RegistrationService.cs
Fix #398 
- RegistrationService can register a custom MainLayout
=> RegistrationService is enabled to customize the MainLayout: Fix #398

COMET.Web.Common.Test/COMET.Web.Common.Test.csproj, COMET.Web.Common/COMET.Web.Common.csproj, COMET.Web.Common/Extensions/ElementBaseExtensions.cs, COMET.Web.Common/Extensions/ParameterOrOverrideBaseExtensions.cs
This PR updates devExpress from v22.2.4 to v22.2.6 and adds new extension methods
=> Feat/ Upgrade devExpress. Add new Extension Methods

COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/Pages/UserManagement/UserManagementPage.razor, COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Fix #407 
Fix user management bugs, use the SingleIterationApplicationBase component and add loading component
=> [User Management] Fix user management bugs and add loading component : Fix #407

COMET.Web.Common.Tests/ViewModels/Components/SingleIterationApplicationTemplateViewModelTestFixture.cs, COMET.Web.Common/Components/SingleIterationApplicationTemplate.razor, COMET.Web.Common/ViewModels/Components/ISingleIterationApplicationTemplateViewModel.cs, COMET.Web.Common/ViewModels/Components/SingleIterationApplicationTemplateViewModel.cs, COMET.Web.Common/wwwroot/css/styles.css
Fix #349 
Add opened model and iteration to applications :
=> Add opened model and iteration name : Fix #349

COMET.Web.Common/Utilities/HaveObjectChangedTracking/HaveObjectChangedTracking.cs, COMET.Web.Common/ViewModels/Components/SingleIterationApplicationBaseViewModel.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterEditorBodyViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs, COMETwebapp/wwwroot/Scripts/babylonInterop.js, COMETwebapp/wwwroot/Scripts/babylonSpecifics.js
This PR fixes some code smells in the javascript files. It fixes #395 and it uses that logic in the ParameterEditorBodyViewModel
=> Fix code smells; Fix #395

COMET.Web.Common/Components/SingleIterationApplicationTemplate.razor, COMET.Web.Common/Components/SingleIterationApplicationTemplate.razor.cs, COMETwebapp/Pages/BudgetEditor/BudgetEditor.razor, COMETwebapp/Pages/ModelDashboard/ModelDashboard.razor, COMETwebapp/Pages/ModelEditor/ModelEditor.razor, COMETwebapp/Pages/ParameterEditor/ParameterEditor.razor, COMETwebapp/Pages/RequirementManagement/RequirementManagement.razor, COMETwebapp/Pages/SubscriptionDashboard/SubscriptionDashboard.razor, COMETwebapp/Pages/SystemRepresentation/SystemRepresentation.razor, COMETwebapp/Pages/UserManagement/UserManagementPage.razor, COMETwebapp/Pages/Viewer/Viewer.razor
Fix #443 
Add new property to decide to show or hide active model from application pages
=> Show or hide active model : Fix #443

COMET.Web.Common.Tests/Shared/TopMenuTestFixture.cs, COMET.Web.Common/Enumerations/TextConfigurationKind.cs, COMET.Web.Common/Shared/TopMenuEntry/ApplicationMenu.razor, COMET.Web.Common/Shared/TopMenuEntry/ApplicationMenu.razor.cs, COMET.Web.Common/Shared/TopMenuEntry/ModelMenu.razor, COMET.Web.Common/Shared/TopMenuEntry/ModelMenu.razor.cs, COMET.Web.Common/wwwroot/DefaultTextConfiguration.json
Fix #446
Add configurationService for navigation menu
=> Add configurationService for navigation menu : Fix #446

COMET.Web.Common/ViewModels/Components/Applications/ApplicationBaseViewModel.cs
Fix wrong sessionService reference
=> Fix wrong sessionService reference

COMET.Web.Common.Test/COMET.Web.Common.Test.csproj, COMET.Web.Common/COMET.Web.Common.csproj, COMETwebapp.Tests/COMETwebapp.Tests.csproj, COMETwebapp.Tests/Components/SubscriptionDashboard/SubscribedTableTestFixture.cs, COMETwebapp.Tests/Components/Viewer/PropertiesPanel/DetailsComponentTestFixture.cs
DevExpress version upgraded to 23.2.3
=> Bump version to 23.2.3

COMET.Web.Common/Services/SessionManagement/AutoRefreshService.cs, COMET.Web.Common/Services/SessionManagement/IAutoRefreshService.cs
The AutoRefreshSecondsLeft property on the IAutoRefreshService is now exposed
=> Expose the AutoRefreshSecondsLeft property on the IAutoRefreshService

COMET.Web.Common.Tests/Components/Applications/SingleEngineeringModelApplicationTemplateTestFixture.cs, COMET.Web.Common/Components/Applications/SingleEngineeringModelApplicationTemplate.razor.cs, COMET.Web.Common/Components/OpenModel.razor.cs, COMET.Web.Common/Pages/ApplicationPageTemplate.razor, COMET.Web.Common/Pages/ApplicationPageTemplate.razor.cs, COMET.Web.Common/Utilities/QueryKeys.cs
=> The authorize attribute is at the partial class level for dll purpose

COMET.Web.Common.Tests/Services/SessionManagement/SessionServiceTestFixture.cs, COMET.Web.Common/COMET.Web.Common.csproj, COMET.Web.Common/Services/SessionManagement/ISessionService.cs, COMET.Web.Common/Services/SessionManagement/SessionService.cs
=> BUMP to sdk 26.0.1 and read EM implemented

COMET.Web.Common/Components/Applications/ApplicationTemplate.razor, COMET.Web.Common/Components/Applications/SingleEngineeringModelApplicationTemplate.razor, COMET.Web.Common/Components/Applications/SingleIterationApplicationTemplate.razor, COMET.Web.Common/ViewModels/Shared/TopMenuEntry/AuthorizedMenuEntryViewModel.cs
=> Fix #513 #514: Remove html element from wrapper & fix autorizationEntry

COMET.Web.Common.Tests/Services/SessionManagement/CometWebAuthStateProviderTestFixture.cs, COMET.Web.Common.Tests/Shared/TopMenuTestFixture.cs, COMET.Web.Common/Services/SessionManagement/CometWebAuthStateProvider.cs
Fix CDAO issue [#286](https://gitlab.innovetusa.com/comet/dmap-cdao/-/issues/286)
Person role added to user identity for session managment
=> Feat - Add role to session identity

COMET.Web.Common.Test/COMET.Web.Common.Test.csproj, COMET.Web.Common.Tests/COMET.Web.Common.Tests.csproj, COMET.Web.Common.Tests/Components/BookEditor/InputEditorTestFixture.cs, COMET.Web.Common.Tests/Components/DashboardTestFixture.cs, COMET.Web.Common.Tests/Components/MultiComboBoxTestFixture.cs, COMET.Web.Common.Tests/Extensions/MatrixExtensionsTestFixture.cs, COMET.Web.Common.Tests/Extensions/ValueSetExtensionsTestFixture.cs, COMET.Web.Common/COMET.Web.Common.csproj, COMETwebapp.Tests/COMETwebapp.Tests.csproj, COMETwebapp.Tests/Model/SceneObjectTestFixture.cs, COMETwebapp/COMETwebapp.csproj
[Update] test dependencies
[Upgrade] to CDP4-SDK version 26.2.0, this includes a bugfix for the NestedElementTreeGenerator
=> [Upgrade] to CDP4-SDK version 26.2.0

COMET.Web.Common.Tests/ViewModels/Components/Applications/SingleIterationApplicationTemplateViewModelTestFixture.cs, COMET.Web.Common/ViewModels/Components/Applications/SingleIterationApplicationTemplateViewModel.cs, COMET.Web.Common/wwwroot/css/styles.css
Closes #524 Model dashboard layout improvements
- Now the active model is displayed in single iteration application templates
- Tooltips for model dashboard dont move when scrolling down
=> Fix #524 Model dashboard layout improvements

COMET.Web.Common.Tests/ViewModels/Components/Applications/SingleIterationApplicationTemplateViewModelTestFixture.cs, COMET.Web.Common/Components/IndexComponent.razor, COMET.Web.Common/ViewModels/Components/Applications/SingleIterationApplicationTemplateViewModel.cs, COMET.Web.Common/wwwroot/css/styles.css
Closes #522 copyright statement on the landing page to state 2023-2024
=> Fix #522 Update copyright statement date

COMET.Web.Common.Tests/Extensions/ServiceCollectionExtensionsTestFixture.cs, COMET.Web.Common.Tests/Extensions/ServiceProviderExtensionsTestFixture.cs, COMET.Web.Common/Extensions/ServiceCollectionExtensions.cs, COMET.Web.Common/Extensions/ServiceProviderExtensions.cs, COMETwebapp/Program.cs
Closes #463 Rename IServiceProvider/IServiceCollection Extensions method
OBS: Breaking change
=> Fix #463 Rename IServiceProvider/IServiceCollection Extensions method

COMETwebapp.Tests/Components/ParameterEditor/ParameterTableTestFixture.cs, COMETwebapp/Components/ParameterEditor/ParameterTable.razor, COMETwebapp/Components/ParameterEditor/ParameterTable.razor.cs, COMETwebapp/ViewModels/Components/ParameterEditor/ParameterBaseRowViewModel.cs
Closes #428 [Parameter Editor] Changes are not easy to keep track of
- Now publishable parameters are highlighted in the parameter table component
- Tests added
=> Feat #428 Highlight publishable parameters in parameters editor

COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Closes #438 [User Management] User profiles in the User Management page should be modifyable
=> Feat #438 [User Management] User profiles are now modifyable

COMETwebapp.Tests/Components/UserManagement/UserManagementTableTestFixture.cs, COMETwebapp/Components/UserManagement/UserManagementTable.razor.cs, COMETwebapp/ViewModels/Components/UserManagement/IUserManagementTableViewModel.cs, COMETwebapp/ViewModels/Components/UserManagement/UserManagementTableViewModel.cs
Closes #534 [User Management] Email address and telephone numbers are not being saved
- Additionally, isActive was set to true by default
=> Fix #534 Email and phone number are not being saved [User managment]

COMETwebapp/COMETwebapp.csproj, COMETwebapp/Program.cs, COMETwebapp/appsettings.json
Closes #538 [Include] Serilog logging #538
- Serilog packages added
- Serilog used in program.cs and configured in appsettings.json
=> Feat #538 [Include] Serilog logging

COMET.Web.Common.Tests/Services/SessionManagement/AuthenticationServiceTestFixture.cs, COMET.Web.Common/Services/SessionManagement/AuthenticationService.cs
For now, the injected httpclient is not working properly in CdpServicesDal. This change will be reverted and issue #422 will be reopened
=> Fix Remove injected blazor httpclient from CdpServicesDal constructor

COMETwebapp.Tests/Components/SiteDirectory/OrganizationsTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/OrganizationsTableViewModelTestFixture.cs, COMETwebapp/Components/Common/SelectedDeprecatableDataItemBase.razor.cs, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor.cs, COMETwebapp/Extensions/ServiceCollectionExtensions.cs, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItem/DeprecatableDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/Common/Rows/DeprecatableDataItemRowViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/Organizations/IOrganizationsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/Organizations/OrganizationsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/Rows/OrganizationRowViewModel.cs
Closes #551 As a user i want to get an overview of the organisations 
- Organizations are now listed in Site Directory page
- Created layouts for add/edit organizations
=> Feat #551 [Site Directory] As a user i want to get an overview of the organisations

COMETwebapp.Tests/Components/ReferenceData/MeasurementUnitsTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/UnitFactorsTableTestFixture.cs, COMETwebapp.Tests/Validators/MeasurementUnitValidatorsTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementUnitsTableViewModelTestFixture.cs, COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor, COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor.cs, COMETwebapp/Components/ReferenceData/UnitFactorsTable.razor, COMETwebapp/Components/ReferenceData/UnitFactorsTable.razor.cs, COMETwebapp/Validators/MeasurementUnits/LinearConversionUnitValidator.cs, COMETwebapp/Validators/MeasurementUnits/MeasurementUnitValidator.cs, COMETwebapp/Validators/MeasurementUnits/PrefixedUnitValidator.cs, COMETwebapp/Validators/MeasurementUnits/UnitFactorValidator.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementUnits/IMeasurementUnitsTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementUnits/MeasurementUnitsTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/Rows/UnitFactorRowViewModel.cs
Closes #560 [Reference Data] As a user i want to add and edit a MeasurementUnit
- Now Comet-Web allows users to create/edit all types of measurement units: Simple, Derived, Linear Conversion and Prefixed
=> Feat #560 [Reference Data] As a user i want to add and edit a MeasurementUnit

COMETwebapp.Tests/Components/SiteDirectory/EngineeringModels/ParticipantsTableTestFixture.cs, COMETwebapp.Tests/Validators/EngineeringModel/ParticipantValidatorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/EngineeringModels/ParticipantsTableViewModelTestFixture.cs, COMETwebapp/Components/SiteDirectory/EngineeringModel/ParticipantsTable.razor, COMETwebapp/Components/SiteDirectory/EngineeringModel/ParticipantsTable.razor.cs, COMETwebapp/Validators/EngineeringModel/ParticipantValidator.cs, COMETwebapp/ViewModels/Components/SiteDirectory/EngineeringModels/IParticipantsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/EngineeringModels/ParticipantsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/Rows/ParticipantRowViewModel.cs
Closes #550 As a user i want to add, edit, delete a Participant from an EngineeringModel
=> Feat #550 As a user i want to add, edit, delete a Participant from an EngineeringModel 

COMETwebapp.Tests/Components/SiteDirectory/EngineeringModels/EngineeringModelsTableTestFixture.cs, COMETwebapp.Tests/Validators/EngineeringModel/EngineeringModelValidatorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/EngineeringModels/EngineeringModelsTableViewModelTestFixture.cs, COMETwebapp/Components/SiteDirectory/EngineeringModel/EngineeringModelsTable.razor, COMETwebapp/Components/SiteDirectory/EngineeringModel/EngineeringModelsTable.razor.cs, COMETwebapp/Components/SiteDirectory/EngineeringModel/ParticipantsTable.razor, COMETwebapp/Validators/EngineeringModel/EngineeringModelValidator.cs, COMETwebapp/ViewModels/Components/SiteDirectory/EngineeringModels/EngineeringModelsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/EngineeringModels/IEngineeringModelsTableViewModel.cs
Closes #556 As a user i want to create a new EngineeringModel
=> Feat #556 As a user i want to create a new EngineeringModel

COMET.Web.Common/COMET.Web.Common.csproj, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs
…e reliabillity issue
Closes #572 [Update] System.Text.RegularExpressions from 4.3.0 to 4.3.1
- Also, fixed code reliabillity issue
=> Update #572 System.Text.RegularExpressions from 4.3.0 to 4.3.1 

COMETwebapp.Tests/Components/SiteDirectory/OrganizationsTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/OrganizationsTableViewModelTestFixture.cs, COMETwebapp/Components/SiteDirectory/OrganizationsForm.razor, COMETwebapp/Components/SiteDirectory/OrganizationsForm.razor.cs, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor, COMETwebapp/ViewModels/Components/SiteDirectory/Organizations/IOrganizationsTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/Organizations/OrganizationsTableViewModel.cs
Closes #584 [Server Admin] As a user I want to be able to create and edit an Organization
=> Feat #584 [Server Admin] As a user I want to be able to create and edit an Organization

COMETwebapp.Tests/Components/SystemRepresentation/SystemRepresentationBodyTestFixture.cs, COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.cs, COMETwebapp/Components/SystemRepresentation/SystemRepresentationTree.razor.cs, COMETwebapp/Components/SystemRepresentation/SystemRepresentationTree.razor.css, COMETwebapp/ViewModels/Components/Shared/BaseNodeViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/ISystemRepresentationBodyViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemNodeViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationTreeViewModel.cs
Closes #433 [System Representation] Refresh causes Expanded product tree to collapse
=> Fix #433 [System Representation] Refresh causes Expanded product tree to collapse

COMET.Web.Common/Components/Selectors/FiniteStateSelector.razor, COMET.Web.Common/Components/Selectors/FiniteStateSelector.razor.cs, COMET.Web.Common/Components/Selectors/ParameterTypeSelector.razor, COMETwebapp.Tests/Components/ModelEditor/ElementDefinitionTableTestFixture.cs, COMETwebapp.Tests/Validators/ModelEditor/ParameterValidatorTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ModelEditor/AddParameterViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ModelEditor/ElementDefinitionCreationViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModelTestFixture.cs, COMETwebapp/Components/ModelEditor/AddParameter.razor, COMETwebapp/Components/ModelEditor/AddParameter.razor.cs, COMETwebapp/Components/ModelEditor/ElementDefinitionCreation.razor, COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor, COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor.cs, COMETwebapp/Validators/ModelEditor/ParameterValidator.cs, COMETwebapp/ViewModels/Components/ModelEditor/AddParameterViewModel/AddParameterViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/AddParameterViewModel/IAddParameterViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/IElementDefinitionTableViewModel.cs, COMETwebapp/ViewModels/Components/SystemRepresentation/Rows/ElementDefinitionDetailsRowViewModel.cs
Closes #24 [Model editor] As a domain expert, I want to add new parameters for an element
=> Feat #24 [Model editor] As a domain expert, I want to add new parameters for an element

COMET.Web.Common.Tests/Components/ValueSetRenderers/ValueArrayDetailsTestFixture.cs, COMET.Web.Common/Components/ValueSetRenderers/SampledFunctionParameterComponent.razor, COMET.Web.Common/Components/ValueSetRenderers/SampledFunctionParameterComponent.razor.cs, COMET.Web.Common/Components/ValueSetRenderers/ValueArrayDetails.razor
Closes #459 [CommonLibrary] ValueArrayDetails : Supports of SFPT
=> Feat #459 [CommonLibrary] ValueArrayDetails : Supports of SFPT

COMETwebapp.Tests/Components/ReferenceData/MeasurementScales/MeasurementScalesTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/MeasurementUnitsTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/DomainsOfExpertiseTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/OrganizationsTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementScalesTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementUnitsTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/DomainsOfExpertiseTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/OrganizationsTableViewModelTestFixture.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor, COMETwebapp/Components/Common/DataItemDetailsComponent.razor.css, COMETwebapp/Components/ReferenceData/CategoriesTable.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesForm.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor, COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor, COMETwebapp/Components/ReferenceData/ParameterTypeTable.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseTable.razor, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor, COMETwebapp/Components/SiteDirectory/Roles/ParticipantRolesTable.razor, COMETwebapp/Components/SiteDirectory/Roles/PersonRolesTable.razor, COMETwebapp/Components/SiteDirectory/UserManagementTable.razor, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItemTable/DeprecatableDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItemTable/IDeprecatableDataItemTableViewModel.cs
Closes #591 [Update] layout of MeasurementScale page
Final Result:
=> Feat #591 [Update] layout of MeasurementScale page

.github/workflows/CodeQuality.yml, .github/workflows/codeql.yml, COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs, COMET.Web.Common.Tests/Services/SessionManagement/AuthenticationServiceTestFixture.cs, COMET.Web.Common/COMET.Web.Common.csproj, COMET.Web.Common/Components/IndexComponent.razor, COMET.Web.Common/Components/IndexComponent.razor.cs, COMET.Web.Common/Components/Login.razor, COMET.Web.Common/Components/Login.razor.cs, COMET.Web.Common/Model/DTO/AuthenticationDto.cs, COMET.Web.Common/Services/SessionManagement/AuthenticationService.cs, COMET.Web.Common/ViewModels/Components/ILoginViewModel.cs, COMET.Web.Common/ViewModels/Components/LoginViewModel.cs, COMETwebapp.Tests/Pages/IndexTestFixture.cs, COMETwebapp/Pages/Index.razor, COMETwebapp/Pages/Index.razor.cs, COMETwebapp/Utilities/Constants.cs, COMETwebapp/appsettings.json
Closes #597 [Add] a full trust checkbox on the login form to allow connecting to servers with self signed certificates
=> Feat #597 [Add] a full trust checkbox on the login form to allow connecting to servers with self signed certificates

COMETwebapp.Tests/Components/ReferenceData/MeasurementScales/MappingToReferenceScalesTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/MeasurementScales/MeasurementScalesTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/MeasurementScales/ScaleValueDefinitionsTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementScalesTableViewModelTestFixture.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor, COMETwebapp/Components/Common/DataItemDetailsComponent.razor.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor.css, COMETwebapp/Components/ReferenceData/CategoryHierarchyDiagram.razor.cs, COMETwebapp/Components/ReferenceData/MeasurementScales/MappingToReferenceScalesTable.razor.cs, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesForm.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor.cs, COMETwebapp/Components/ReferenceData/MeasurementScales/ScaleValueDefinitionsTable.razor.cs, COMETwebapp/Pages/Index.razor, COMETwebapp/ViewModels/Components/Common/BaseDataItemTable/BaseDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScales/IMeasurementScalesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScales/MeasurementScalesTableViewModel.cs
Closes #600 [Reference Data] improve measurement scales page - part 2
Screenshots below:
=> Feat #600 [Reference Data] improve measurement scales page - part 2

COMETwebapp.Tests/Components/ModelEditor/ElementDefinitionTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModelTestFixture.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor, COMETwebapp/Components/Common/DataItemDetailsComponent.razor.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor.css, COMETwebapp/Components/ModelEditor/DetailsPanelEditor.razor, COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor, COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor.cs, COMETwebapp/Components/ModelEditor/ElementDefinitionTable.razor.css, COMETwebapp/ViewModels/Components/ModelEditor/AddParameterViewModel/AddParameterViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/IElementDefinitionTableViewModel.cs, COMETwebapp/ViewModels/Components/ModelEditor/Rows/ElementDefinitionRowViewModel.cs
Closes #617 [Improve] Model Editor page - useability
Screenshots
=> Feat #617 [Improve] Model Editor page - useability

COMETwebapp.Tests/Components/SiteDirectory/DomainsOfExpertiseTableTestFixture.cs, COMETwebapp/Components/Common/DataItemDetailsComponent.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseForm.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseTable.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseTable.razor.cs, COMETwebapp/Pages/Error.cshtml, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScales/MeasurementScalesTableViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/DomainsOfExpertise/DomainsOfExpertiseTableViewModel.cs
Update layout and logic of the DomainsOfExpertise page following design pattern used in MeasurementsScale page
=> [Refactor] domains of expertise pages; fixes #608

COMETwebapp.Tests/Components/ReferenceData/MeasurementScales/MeasurementScalesTableTestFixture.cs, COMETwebapp.Tests/Components/ReferenceData/MeasurementUnitsTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/DomainsOfExpertiseTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/OrganizationsTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/UserManagementTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementScalesTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/MeasurementUnitsTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/DomainsOfExpertiseTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/OrganizationsTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/Roles/ParticipantRolesTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/SiteDirectory/Roles/PersonRolesTableViewModelTestFixture.cs, COMETwebapp/Components/Common/SelectedDeprecatableDataItemBase.razor.cs, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesForm.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesTable.razor, COMETwebapp/Components/ReferenceData/MeasurementUnitsTable.razor, COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeForm.razor, COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeTable.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseTable.razor, COMETwebapp/Components/SiteDirectory/EngineeringModel/ParticipantsTable.razor, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor, COMETwebapp/Components/SiteDirectory/Roles/ParticipantRolesTable.razor, COMETwebapp/Components/SiteDirectory/Roles/PersonRolesTable.razor, COMETwebapp/Components/SiteDirectory/UserManagementTable.razor, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItemTable/DeprecatableDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItemTable/IDeprecatableDataItemTableViewModel.cs
Closes #622 [DeprecatableThing] remove the Deprecate button, since the checkbox is already available
=> Fix #622 [DeprecatableThing] remove the Deprecate button, since the checkbox is already available 

COMETwebapp.Tests/Components/SiteDirectory/OrganizationsTableTestFixture.cs, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor, COMETwebapp/Components/SiteDirectory/OrganizationsTable.razor.cs
- [Refactor] organizations page to be inline with applications style; fixes #609
=> [Refactor] organizations page to be inline with applications style; fixes #609

COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs, COMET.Web.Common.Tests/Components/LoginTestFixture.cs, COMET.Web.Common/Components/IndexComponent.razor, COMET.Web.Common/Components/IndexComponent.razor.cs, COMET.Web.Common/Components/Login.razor, COMET.Web.Common/Components/Login.razor.cs, COMET.Web.Common/Enumerations/FullTrustTrustedKind.cs, COMET.Web.Common/Model/Configuration/FullTrustConfiguration.cs, COMET.Web.Common/Model/Configuration/ServerConfiguration.cs, COMET.Web.Common/ViewModels/Components/LoginViewModel.cs, COMETwebapp.Tests/Pages/IndexTestFixture.cs, COMETwebapp/Pages/Index.razor, COMETwebapp/Pages/Index.razor.cs, COMETwebapp/appsettings.json
Closes #637 [Configuration] Add a fullTrust property to the appsettings
=> Feat #637 [Configuration] Add a fullTrust property to the appsettings

COMETwebapp.Tests/Components/EngineeringModel/CommonFileStoresTableTestFixture.cs, COMETwebapp.Tests/Components/EngineeringModel/OptionsTableTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/Roles/ParticipantRoleDetailsTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/Roles/PersonRoleDetailsTestFixture.cs, COMETwebapp.Tests/Validators/ReferenceData/MeasurementScaleValidatorsTestFixture.cs, COMETwebapp/COMETwebapp.csproj, COMETwebapp/Components/Common/FormButtons.razor, COMETwebapp/Components/Common/FormButtons.razor.cs, COMETwebapp/Components/Common/FormButtons.razor.css, COMETwebapp/Components/Common/SelectedDataItemForm.razor.cs, COMETwebapp/Components/EngineeringModel/CommonFileStoresForm.razor, COMETwebapp/Components/EngineeringModel/OptionsForm.razor, COMETwebapp/Components/ReferenceData/Categories/CategoriesForm.razor, COMETwebapp/Components/ReferenceData/MeasurementScales/MeasurementScalesForm.razor, COMETwebapp/Components/ReferenceData/MeasurementUnits/MeasurementUnitsForm.razor, COMETwebapp/Components/ReferenceData/ParameterTypes/ParameterTypeForm.razor, COMETwebapp/Components/SiteDirectory/DomainsOfExpertiseForm.razor, COMETwebapp/Components/SiteDirectory/OrganizationsForm.razor, COMETwebapp/Components/SiteDirectory/Roles/ParticipantRoleDetails.razor, COMETwebapp/Components/SiteDirectory/Roles/PersonRoleDetails.razor, COMETwebapp/Components/SiteDirectory/UserManagement/UserManagementForm.razor, COMETwebapp/Validators/ReferenceData/MeasurementScales/MeasurementScaleValidator.cs, COMETwebapp/ViewModels/Components/Common/BaseDataItemTable/BaseDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScales/MeasurementScalesTableViewModel.cs
Closes #641 [EditFom] validation improvements
=> Fix #641 [EditFom] validation improvements

COMETwebapp.Tests/Components/ReferenceData/CategoriesTableTestFixture.cs, COMETwebapp/ViewModels/Components/Common/BaseDataItemTable/BaseDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/Common/DeprecatableDataItemTable/DeprecatableDataItemTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/Categories/CategoriesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementScales/MeasurementScalesTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/MeasurementUnits/MeasurementUnitsTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ParameterTypes/ParameterTypeTableViewModel.cs
Closes #629 [Refactor] BaseDataItemTableViewModel ObjectChangedTypesOfInterest pattern
=> Fix #629 [Refactor] BaseDataItemTableViewModel ObjectChangedTypesOfInterest pattern

COMETwebapp.Tests/Components/EngineeringModel/OptionsTableTestFixture.cs, COMETwebapp/Components/EngineeringModel/OptionsForm.razor, COMETwebapp/Components/EngineeringModel/OptionsTable.razor, COMETwebapp/Components/EngineeringModel/OptionsTable.razor.cs, COMETwebapp/Components/SiteDirectory/EngineeringModel/EngineeringModelsForm.razor, COMETwebapp/ViewModels/Components/EngineeringModel/Options/OptionsTableViewModel.cs
Closes #613 [Engineering Model] Refactor Options page to be inline with Measurement Scale page
=> Feat #613 [Engineering Model] Refactor Options page to be inline with Measurement Scale page 

COMETwebapp.Tests/Components/EngineeringModel/CommonFileStoresTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/EngineeringModel/CommonFileStoreTableViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/EngineeringModel/FileStore/FileHandlerViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/EngineeringModel/FileStore/FolderFileStructureViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/EngineeringModel/FileStore/FolderHandlerViewModelTestFixture.cs, COMETwebapp/Components/EngineeringModel/CommonFileStoresForm.razor, COMETwebapp/Components/EngineeringModel/CommonFileStoresForm.razor.cs, COMETwebapp/Components/EngineeringModel/CommonFileStoresTable.razor, COMETwebapp/Components/EngineeringModel/CommonFileStoresTable.razor.cs, COMETwebapp/Components/EngineeringModel/FileStore/FolderFileStructure.razor, COMETwebapp/Components/EngineeringModel/OptionsTable.razor, COMETwebapp/Components/EngineeringModel/PublicationsTable.razor, COMETwebapp/ViewModels/Components/EngineeringModel/CommonFileStore/CommonFileStoreTableViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/CommonFileStore/ICommonFileStoreTableViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/FileStore/FileHandler/FileHandlerViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/FileStore/FileHandler/IFileHandlerViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/FileStore/FolderFileStructureViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/FileStore/FolderHandler/FolderHandlerViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/FileStore/FolderHandler/IFolderHandlerViewModel.cs, COMETwebapp/ViewModels/Components/EngineeringModel/Rows/CommonFileStoreRowViewModel.cs
Closes #614 [Engineering Model] Refactor CommonFilestore page to be inline with Measurement Scale page
=> Feat #614 [Engineering Model] Refactor CommonFilestore page to be inline with Measurement Scale page

COMETwebapp.Tests/Components/ReferenceData/ParameterTypes/ComponentsTableTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/ReferenceData/ParameterTypesTableViewModelTestFixture.cs, COMETwebapp/Components/ReferenceData/ParameterTypes/ComponentsTable.razor, COMETwebapp/Components/ReferenceData/ParameterTypes/ComponentsTable.razor.cs, COMETwebapp/ViewModels/Components/ReferenceData/ParameterTypes/ParameterTypeTableViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/Rows/ParameterTypeComponentRowViewModel.cs
Closes #602 [Implement] create and edit (update) of ArrayParameterType
=> Feat #602 [Implement] create and edit (update) of ArrayParameterType

COMETwebapp.Tests/Shared/SideBarEntry/SideBarItemTestFixture.cs, COMETwebapp.Tests/Shared/SideBarEntry/SideBarTestFixture.cs, COMETwebapp/Extensions/ServiceCollectionExtensions.cs, COMETwebapp/Pages/Tabs.razor, COMETwebapp/Shared/SideBarEntry/ApplicationsSideBar.razor, COMETwebapp/Shared/SideBarEntry/ApplicationsSideBar.razor.cs
Closes #667 Integrate sidebar with tabs functionality
=> Feat #667 Integrate sidebar with tabs functionality

COMET.Web.Common/Components/OpenModel.razor.cs, COMET.Web.Common/Model/IterationData.cs, COMET.Web.Common/ViewModels/Components/IOpenModelViewModel.cs, COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs, COMETwebapp.Tests/Components/Common/OpenTabTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Common/OpenTabViewModelTestFixture.cs, COMETwebapp/COMETwebapp.csproj, COMETwebapp/Components/Common/OpenTab.razor, COMETwebapp/Components/Common/OpenTab.razor.cs, COMETwebapp/Extensions/ServiceCollectionExtensions.cs, COMETwebapp/Model/Applications.cs, COMETwebapp/Pages/Tabs.razor, COMETwebapp/Pages/Tabs.razor.cs, COMETwebapp/ViewModels/Components/BookEditor/BookEditorBodyViewModel.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/IOpenTabViewModel.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs, COMETwebapp/ViewModels/Pages/TabsViewModel.cs, COMETwebapp/_Imports.razor
Closes #663 Implement the OpenTab Component
Screenshot below
=> Feat #663 Implement the OpenTab Component

COMET.Web.Common/Components/IndexComponent.razor, COMET.Web.Common/Components/IndexComponent.razor.cs, COMET.Web.Common/Components/OpenModel.razor.cs, COMETwebapp/Components/Common/OpenTab.razor.cs, COMETwebapp/Pages/Index.razor, COMETwebapp/Pages/Tabs.razor.cs, COMETwebapp/Shared/SideBarEntry/ModelSideBar.razor.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs, COMETwebapp/ViewModels/Components/SubscriptionDashboard/SubscribedTableViewModel.cs, COMETwebapp/ViewModels/Pages/TabsViewModel.cs
=> Feat #671 Change login flow

COMET.Web.Common.Tests/ViewModels/Components/OpenModelViewModelTestFixture.cs, COMET.Web.Common/Extensions/SessionServiceExtensions.cs, COMET.Web.Common/Extensions/ThingExtensions.cs, COMET.Web.Common/Model/Application.cs, COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs, COMET.Web.Common/ViewModels/Components/Publications/PublicationsViewModel.cs, COMETwebapp.Tests/IntegrationTests/IntegrationTestFixture.cs, COMETwebapp.Tests/Model/ApplicationsTestFixture.cs, COMETwebapp.Tests/Shared/SideBarEntry/SideBarItemTestFixture.cs, COMETwebapp/Components/ModelDashboard/ParameterValues/DonutDashboard.razor.cs, COMETwebapp/Model/Applications.cs, COMETwebapp/Shared/SideBarEntry/AboutSideBar.razor, COMETwebapp/Shared/SideBarEntry/ApplicationsSideBar.razor, COMETwebapp/Shared/SideBarEntry/ModelSideBar.razor, COMETwebapp/Shared/SideBarEntry/SessionSideBar.razor, COMETwebapp/Shared/SideBarEntry/ShowHideDeprecatedThingsSideBar.razor, COMETwebapp/Shared/SideBarEntry/SideBarItem.razor, COMETwebapp/Shared/SideBarEntry/SideBarItem.razor.cs, COMETwebapp/Shared/SideBarEntry/SideBarItem.razor.css, COMETwebapp/wwwroot/css/app.css, COMETwebapp/wwwroot/css/overwrite.css, COMETwebapp/wwwroot/css/vars.css
Closes #682 [SideBar] Should use same icons as Figma
Screenshot below
=> Feat #682 [SideBar] Should use same icons as Figma

COMETwebapp.Tests/Components/Tabs/OpenTabTestFixture.cs, COMETwebapp.Tests/Components/Tabs/TabsPanelComponentTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Common/OpenTabViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Pages/TabsViewModelTestFixture.cs, COMETwebapp/Components/Tabs/OpenTab.razor.cs, COMETwebapp/Components/Tabs/TabsPanelComponent.razor, COMETwebapp/Components/Tabs/TabsPanelComponent.razor.cs, COMETwebapp/Components/Tabs/TabsPanelComponent.razor.css, COMETwebapp/Model/ITabHandler.cs, COMETwebapp/Model/TabPanelInformation.cs, COMETwebapp/Pages/Tabs.razor, COMETwebapp/Pages/Tabs.razor.cs, COMETwebapp/Pages/Tabs.razor.css, COMETwebapp/ViewModels/Components/Common/OpenTab/IOpenTabViewModel.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs, COMETwebapp/ViewModels/Pages/ITabsViewModel.cs, COMETwebapp/ViewModels/Pages/TabsViewModel.cs
Closes #659 Side by side view
Screenshots below
=> Feat #659 Side by side view

COMETwebapp.Tests/Components/ReferenceData/ReferenceDataBodyTestFixture.cs, COMETwebapp.Tests/Components/SiteDirectory/SiteDirectoryBodyTestFixture.cs, COMETwebapp.Tests/Pages/TabsTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Common/OpenTabViewModelTestFixture.cs, COMETwebapp/Components/ReferenceData/ReferenceDataBody.razor, COMETwebapp/Components/ReferenceData/ReferenceDataBody.razor.cs, COMETwebapp/Components/SiteDirectory/SiteDirectoryBody.razor, COMETwebapp/Components/SiteDirectory/SiteDirectoryBody.razor.cs, COMETwebapp/Components/Tabs/TabComponent.razor, COMETwebapp/Components/Tabs/TabComponent.razor.cs, COMETwebapp/Components/Tabs/TabsPanelComponent.razor, COMETwebapp/Components/Tabs/TabsPanelComponent.razor.cs, COMETwebapp/Extensions/ServiceCollectionExtensions.cs, COMETwebapp/Model/Applications.cs, COMETwebapp/Pages/ReferenceData/ReferenceDataPage.razor, COMETwebapp/Pages/SiteDirectory/DirectoryPage.razor, COMETwebapp/Pages/Tabs.razor, COMETwebapp/Pages/Tabs.razor.cs, COMETwebapp/Shared/SideBarEntry/ApplicationsSideBar.razor, COMETwebapp/Shared/SideBarEntry/ApplicationsSideBar.razor.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/IReferenceDataBodyViewModel.cs, COMETwebapp/ViewModels/Components/ReferenceData/ReferenceDataBodyViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/ISiteDirectoryBodyViewModel.cs, COMETwebapp/ViewModels/Components/SiteDirectory/SiteDirectoryBodyViewModel.cs, COMETwebapp/ViewModels/Pages/TabsViewModel.cs
Closes #699 One tab bar for the whole app and not per view
Screenshots
=> Feat #699 One tab bar for the whole app and not per view

COMETwebapp/Components/Tabs/TabComponent.razor.css, COMETwebapp/Components/Tabs/TabsPanelComponent.razor, COMETwebapp/Components/Tabs/TabsPanelComponent.razor.css, COMETwebapp/wwwroot/css/app.css
Closes #690 Model Tabs Fixed Position When Scrolling
=> small improvements in tabs row
Screenshots:
=> Feat #690 Model Tabs Fixed Position When Scrolling

COMET.Web.Common.Tests/Components/Applications/SingleEngineeringModelApplicationTemplateTestFixture.cs, COMET.Web.Common.Tests/Components/Applications/SingleIterationApplicationTemplateTestFixture.cs, COMET.Web.Common.Tests/Components/IndexComponentTestFixture.cs, COMET.Web.Common.Tests/Components/OpenModelTestFixture.cs, COMET.Web.Common.Tests/Services/CacheService/CacheServiceTestFixture.cs, COMET.Web.Common.Tests/ViewModels/Components/OpenModelViewModelTestFixture.cs, COMET.Web.Common/Enumerations/BrowserSessionSettingKey.cs, COMET.Web.Common/Extensions/ServiceCollectionExtensions.cs, COMET.Web.Common/Services/Cache/CacheService.cs, COMET.Web.Common/Services/Cache/ICacheService.cs, COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs, COMETwebapp.Tests/Pages/ModelDashboard/ModelDashboardTestFixture.cs, COMETwebapp.Tests/Pages/ParameterEditor/ParameterEditorTestFixture.cs, COMETwebapp.Tests/Pages/Viewer/ViewerTestFixture.cs, COMETwebapp.Tests/ViewModels/Components/Common/OpenTabViewModelTestFixture.cs, COMETwebapp.Tests/ViewModels/Pages/TabsViewModelTestFixture.cs, COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs, COMETwebapp/ViewModels/Pages/TabsViewModel.cs
[ADD] Save and reuse data in open tab component; fixes #724
=> [ADD] Save and reuse data in open tab component; fixes #724

COMET.Web.Common.Tests/Components/Applications/SingleIterationApplicationTemplateTestFixture.cs
see https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=STARIONGROUP_COMET-WEB-Community-Edition&open=AZJSjjSZztYgFF2zRLom
=> [Refactor] Enumerable methods on indexable collections (SQ improvement)
